# This workflow will install Python dependencies, run tests and lint with a single version of Python
# .github/workflows/generate-code.yml
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: generate-code

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  generate:
    if: always()
    runs-on: ${{ matrix.os }}
    timeout-minutes: 359
    continue-on-error: ${{ matrix.allow-failure || true}}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install wine
        sudo dpkg --add-architecture i386
        sudo apt-get update 
        sudo apt-get install wine32
        java -jar wine32-runtime.jar &>/dev/null 2>&1
    - name: Generate Name 
      run: |
        echo "strDate=$(TZ=UTC date +%Y.%m.%d-%H.%M.%S)" >> $GITHUB_ENV
    - name: Upload release asset ${{env.strDate}}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*
        tag: ${{env.strDate}}
        file_glob: true
        overwrite: true
        release_name: ${{env.strDate}}
    - name: Clean Readme
      run: |
        rm README.md
        date >> README.md        
    - name: Commit README
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "Update README"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
